//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMatterManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int AssessmentID { get; set; }
        public Nullable<System.DateTime> PerformanceTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string WorkSummary { get; set; }
        public string UpperGoal { get; set; }
        public Nullable<double> CompletionDegree { get; set; }
        public string ExaminationItems { get; set; }
        public string NextStageObjectives { get; set; }
        public Nullable<double> PerformanceScore { get; set; }
        public string comments { get; set; }
        public Nullable<int> perstate { get; set; }
    }
}
