//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMatterManager.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRCEntities : DbContext
    {
        public HRCEntities()
            : base("name=HRCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assessment> Assessment { get; set; }
        public virtual DbSet<AttendanceSheet> AttendanceSheet { get; set; }
        public virtual DbSet<CategoryItems> CategoryItems { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Leave> Leave { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<Overtime> Overtime { get; set; }
        public virtual DbSet<OvertimeCheck> OvertimeCheck { get; set; }
        public virtual DbSet<PayRise> PayRise { get; set; }
        public virtual DbSet<PaySlip> PaySlip { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<SystemLog> SystemLog { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
