//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMatterManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overtime
    {
        public int OvertimeID { get; set; }
        public Nullable<System.DateTime> OvertimeStateTime { get; set; }
        public Nullable<System.DateTime> OvertimeEndTime { get; set; }
        public Nullable<int> OvertimeDuration { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<int> OvertimeState { get; set; }
        public string ApproverReason { get; set; }
    }
}
