//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonMatterManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> AttendanceBonus { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<System.DateTime> SalaryTime { get; set; }
        public Nullable<decimal> SalarySum { get; set; }
    }
}
